# Generated by Django 4.0 on 2023-10-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingID', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
