# Generated by Django 4.0 on 2023-10-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_customuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
