# Generated by Django 4.0 on 2023-10-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default=12121212, max_length=15),
            preserve_default=False,
        ),
    ]
