# Generated by Django 4.0 on 2023-11-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
